name: ibamedt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1 
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  firebase_app_check: ^0.3.2+4 
  image_cropper: ^9.0.0
  google_sign_in: ^5.3.0
  flutter_animate: ^4.1.1
  lottie: ^2.3.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/  # Assurez-vous que ce dossier existe dans votre projet
